#!/usr/bin/env python3
"""
parse_axiom_output.py <lean_stdout_file> <names_file>

Parses the REAL output of running `#print axioms <name>` for every theorem
(produced by CheckAllAxioms.lean, generated by make_axiom_probe.py, and run
through the actual Lean compiler in the GitHub Actions job).

Lean's `#print axioms` command emits one of:
    'name' does not depend on any axioms
    'name' depends on axioms: [propext, Classical.choice, Quot.sound]
or an error (unknown identifier, etc.) if the name didn't resolve.

Status assigned per theorem, based on the REAL axiom list, not an assumption:
    proved         — no axioms, or only the three standard Mathlib axioms
                     (propext, Classical.choice, Quot.sound)
    sorry          — depends on `sorryAx` (this is literally what `sorry`
                     compiles to — unambiguous, not a guess)
    extra-axiom    — depends on some other, non-standard axiom (a genuine
                     custom `axiom` declaration somewhere in the chain —
                     this is what "0 extra axioms" should actually mean)
    unresolved     — the name didn't produce a parseable #print axioms
                     result at all (likely a namespace/shadowing issue,
                     not a claim about the proof itself)

Outputs registry.csv with columns: file, kind, name, status, axioms
"""
import csv
import re
import sys

STANDARD_AXIOMS = {"propext", "Classical.choice", "Quot.sound"}

RESULT_RE = re.compile(
    r"'([^']+)'\s+(does not depend on any axioms|depends on axioms:\s*\[(.*?)\])"
)


def classify(axiom_list):
    axioms = set(a.strip() for a in axiom_list if a.strip())
    if "sorryAx" in axioms:
        return "sorry", axioms
    extra = axioms - STANDARD_AXIOMS
    if extra:
        return "extra-axiom", axioms
    return "proved", axioms


def main():
    if len(sys.argv) != 3:
        print("usage: parse_axiom_output.py <lean_stdout_file> <names_file>", file=sys.stderr)
        sys.exit(1)
    stdout_path, names_path = sys.argv[1], sys.argv[2]

    with open(stdout_path, encoding='utf-8', errors='ignore') as f:
        output = f.read()

    results = {}
    for m in RESULT_RE.finditer(output):
        name = m.group(1)
        if m.group(2).startswith("does not depend"):
            status, axioms = "proved", set()
        else:
            axiom_list = m.group(3).split(',')
            status, axioms = classify(axiom_list)
        results[name] = (status, axioms)

    rows = []
    seen = set()
    with open(names_path, encoding='utf-8') as f:
        for line in f:
            line = line.rstrip('\n')
            if not line:
                continue
            parts = line.split('\t')
            if len(parts) != 3:
                continue
            relpath, kind, name = parts
            if name in seen:
                continue
            seen.add(name)
            if name in results:
                status, axioms = results[name]
            else:
                status, axioms = "unresolved", set()
            rows.append({
                "file": relpath,
                "kind": kind,
                "name": name,
                "status": status,
                "axioms": ";".join(sorted(axioms)),
            })

    writer = csv.DictWriter(sys.stdout, fieldnames=["file", "kind", "name", "status", "axioms"])
    writer.writeheader()
    for r in rows:
        writer.writerow(r)


if __name__ == '__main__':
    main()
